name: Node Image Sync

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # schedule:
  # - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Node Image Sync
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Login to Quay
      uses: docker/login-action@v1 
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_TOKEN }}
    
    - name: Run a multi-line script
        run: |
          docker pull node:fermium
          docker tag node:fermium quay.io/ycao56/node:fermium
          docker push quay.io/ycao56/node:fermium

    